package br.com.sicva.model;
// Generated 16/03/2017 15:37:02 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CarteirasVacinas generated by hbm2java
 */
@Entity
@Table(name="carteiras_vacinas"
    ,catalog="sicva"
)
public class CarteirasVacinas  implements java.io.Serializable {


     private Integer carteirasId;
     private Pacientes pacientes;
     private Vacinas vacinas;
     private String carteirasStatus;
     private String carteirasFaixaEtaria;
     private String carteirasPeriodo;
     private Date carteirasProximaData;
     

    public CarteirasVacinas() {
    }

    public CarteirasVacinas(Pacientes pacientes, Vacinas vacinas, String carteirasStatus, String carteirasFaixaEtaria, String carteirasPeriodo, Date carteirasProximaData) {
       this.pacientes = pacientes;
       this.vacinas = vacinas;
       this.carteirasStatus = carteirasStatus;
       this.carteirasFaixaEtaria = carteirasFaixaEtaria;
       this.carteirasPeriodo = carteirasPeriodo;
       this.carteirasProximaData = carteirasProximaData;
       
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="CARTEIRAS_ID", unique=true, nullable=false)
    public Integer getCarteirasId() {
        return this.carteirasId;
    }
    
    public void setCarteirasId(Integer carteirasId) {
        this.carteirasId = carteirasId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CARTEIRAS_PACIENTES_NUMERO_REGISTRO_NASCIMENTO")
    public Pacientes getPacientes() {
        return this.pacientes;
    }
    
    public void setPacientes(Pacientes pacientes) {
        this.pacientes = pacientes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CARTEIRAS_VACINAS_CODIGO")
    public Vacinas getVacinas() {
        return this.vacinas;
    }
    
    public void setVacinas(Vacinas vacinas) {
        this.vacinas = vacinas;
    }

    
    @Column(name="CARTEIRAS_STATUS", length=11)
    public String getCarteirasStatus() {
        return this.carteirasStatus;
    }
    
    public void setCarteirasStatus(String carteirasStatus) {
        this.carteirasStatus = carteirasStatus;
    }

    
    @Column(name="CARTEIRAS_FAIXA_ETARIA", length=10)
    public String getCarteirasFaixaEtaria() {
        return this.carteirasFaixaEtaria;
    }
    
    public void setCarteirasFaixaEtaria(String carteirasFaixaEtaria) {
        this.carteirasFaixaEtaria = carteirasFaixaEtaria;
    }

    
    @Column(name="CARTEIRAS_PERIODO", length=14)
    public String getCarteirasPeriodo() {
        return this.carteirasPeriodo;
    }
    
    public void setCarteirasPeriodo(String carteirasPeriodo) {
        this.carteirasPeriodo = carteirasPeriodo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CARTEIRAS_PROXIMA_DATA", length=10)
    public Date getCarteirasProximaData() {
        return this.carteirasProximaData;
    }
    
    public void setCarteirasProximaData(Date carteirasProximaData) {
        this.carteirasProximaData = carteirasProximaData;
    }


   


}


