package br.com.sicva.model;
// Generated 16/03/2017 13:54:36 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CarteirasVacinas generated by hbm2java
 */
public class CarteirasVacinas  implements java.io.Serializable {


     private Integer carteirasId;
     private Pacientes pacientes;
     private Vacinas vacinas;
     private String carteirasStatus;
     private String carteirasFaixaEtaria;
     private String carteirasPeriodo;
     private Date carteirasProximaData;
     private Set registrosVacinases = new HashSet(0);

    public CarteirasVacinas() {
    }

    public CarteirasVacinas(Pacientes pacientes, Vacinas vacinas, String carteirasStatus, String carteirasFaixaEtaria, String carteirasPeriodo, Date carteirasProximaData, Set registrosVacinases) {
       this.pacientes = pacientes;
       this.vacinas = vacinas;
       this.carteirasStatus = carteirasStatus;
       this.carteirasFaixaEtaria = carteirasFaixaEtaria;
       this.carteirasPeriodo = carteirasPeriodo;
       this.carteirasProximaData = carteirasProximaData;
       this.registrosVacinases = registrosVacinases;
    }
   
    public Integer getCarteirasId() {
        return this.carteirasId;
    }
    
    public void setCarteirasId(Integer carteirasId) {
        this.carteirasId = carteirasId;
    }
    public Pacientes getPacientes() {
        return this.pacientes;
    }
    
    public void setPacientes(Pacientes pacientes) {
        this.pacientes = pacientes;
    }
    public Vacinas getVacinas() {
        return this.vacinas;
    }
    
    public void setVacinas(Vacinas vacinas) {
        this.vacinas = vacinas;
    }
    public String getCarteirasStatus() {
        return this.carteirasStatus;
    }
    
    public void setCarteirasStatus(String carteirasStatus) {
        this.carteirasStatus = carteirasStatus;
    }
    public String getCarteirasFaixaEtaria() {
        return this.carteirasFaixaEtaria;
    }
    
    public void setCarteirasFaixaEtaria(String carteirasFaixaEtaria) {
        this.carteirasFaixaEtaria = carteirasFaixaEtaria;
    }
    public String getCarteirasPeriodo() {
        return this.carteirasPeriodo;
    }
    
    public void setCarteirasPeriodo(String carteirasPeriodo) {
        this.carteirasPeriodo = carteirasPeriodo;
    }
    public Date getCarteirasProximaData() {
        return this.carteirasProximaData;
    }
    
    public void setCarteirasProximaData(Date carteirasProximaData) {
        this.carteirasProximaData = carteirasProximaData;
    }
    public Set getRegistrosVacinases() {
        return this.registrosVacinases;
    }
    
    public void setRegistrosVacinases(Set registrosVacinases) {
        this.registrosVacinases = registrosVacinases;
    }




}


