package br.com.sicva.model;
// Generated 28/03/2017 16:05:59 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Enderecos generated by hbm2java
 */
@Entity
@Table(name="enderecos"
    ,catalog="sicva"
)
public class Enderecos  implements java.io.Serializable {


     private Integer enderecosId;
     private Integer enderecoCep;
     private String enderecoNumero;
     private String enderecoRua;

    public Enderecos() {
    }

    public Enderecos(Integer enderecoCep, String enderecoNumero, String enderecoRua) {
       this.enderecoCep = enderecoCep;
       this.enderecoNumero = enderecoNumero;
       this.enderecoRua = enderecoRua;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ENDERECOS_ID", unique=true, nullable=false)
    public Integer getEnderecosId() {
        return this.enderecosId;
    }
    
    public void setEnderecosId(Integer enderecosId) {
        this.enderecosId = enderecosId;
    }

    
    @Column(name="ENDERECO_CEP")
    public Integer getEnderecoCep() {
        return this.enderecoCep;
    }
    
    public void setEnderecoCep(Integer enderecoCep) {
        this.enderecoCep = enderecoCep;
    }

    
    @Column(name="ENDERECO_NUMERO", length=5)
    public String getEnderecoNumero() {
        return this.enderecoNumero;
    }
    
    public void setEnderecoNumero(String enderecoNumero) {
        this.enderecoNumero = enderecoNumero;
    }

    
    @Column(name="ENDERECO_RUA", length=30)
    public String getEnderecoRua() {
        return this.enderecoRua;
    }
    
    public void setEnderecoRua(String enderecoRua) {
        this.enderecoRua = enderecoRua;
    }




}


