package br.com.sicva.model;
// Generated 16/03/2017 13:54:36 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Funcao generated by hbm2java
 */
public class Funcao  implements java.io.Serializable {


     private String funcaoDescricao;
     private Set usuariosFuncaos = new HashSet(0);

    public Funcao() {
    }

	
    public Funcao(String funcaoDescricao) {
        this.funcaoDescricao = funcaoDescricao;
    }
    public Funcao(String funcaoDescricao, Set usuariosFuncaos) {
       this.funcaoDescricao = funcaoDescricao;
       this.usuariosFuncaos = usuariosFuncaos;
    }
   
    public String getFuncaoDescricao() {
        return this.funcaoDescricao;
    }
    
    public void setFuncaoDescricao(String funcaoDescricao) {
        this.funcaoDescricao = funcaoDescricao;
    }
    public Set getUsuariosFuncaos() {
        return this.usuariosFuncaos;
    }
    
    public void setUsuariosFuncaos(Set usuariosFuncaos) {
        this.usuariosFuncaos = usuariosFuncaos;
    }




}


