package br.com.sicva.model;
// Generated 16/03/2017 15:37:02 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ItensVacinas generated by hbm2java
 */
@Entity
@Table(name="itens_vacinas"
    ,catalog="sicva"
)
public class ItensVacinas  implements java.io.Serializable {


     private Integer itensVacinasCodigo;
     private ItensVacinas itensVacinas;
     private Ubs ubs;
     

    public ItensVacinas() {
    }

    public ItensVacinas(ItensVacinas itensVacinas, Ubs ubs) {
       this.itensVacinas = itensVacinas;
       this.ubs = ubs;
       
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ITENS_VACINAS_CODIGO", unique=true, nullable=false)
    public Integer getItensVacinasCodigo() {
        return this.itensVacinasCodigo;
    }
    
    public void setItensVacinasCodigo(Integer itensVacinasCodigo) {
        this.itensVacinasCodigo = itensVacinasCodigo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ITENS_VACINAS_VACINAS_CODIGO")
    public ItensVacinas getItensVacinas() {
        return this.itensVacinas;
    }
    
    public void setItensVacinas(ItensVacinas itensVacinas) {
        this.itensVacinas = itensVacinas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ITENS_VACINAS_UBS_ID")
    public Ubs getUbs() {
        return this.ubs;
    }
    
    public void setUbs(Ubs ubs) {
        this.ubs = ubs;
    }
   


}


