package br.com.sicva.model;
// Generated 28/03/2017 16:05:59 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ItensVacinas generated by hbm2java
 */
@Entity
@Table(name="itens_vacinas"
    ,catalog="sicva"
)
public class ItensVacinas  implements java.io.Serializable {


     private Integer itensVacinasCodigo;
     private RegistrosVacinas registrosVacinas;
     private Ubs ubs;
     private Vacinas vacinas;

    public ItensVacinas() {
    }

	
    public ItensVacinas(RegistrosVacinas registrosVacinas, Vacinas vacinas) {
        this.registrosVacinas = registrosVacinas;
        this.vacinas = vacinas;
    }
    public ItensVacinas(RegistrosVacinas registrosVacinas, Ubs ubs, Vacinas vacinas) {
       this.registrosVacinas = registrosVacinas;
       this.ubs = ubs;
       this.vacinas = vacinas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ITENS_VACINAS_CODIGO", unique=true, nullable=false)
    public Integer getItensVacinasCodigo() {
        return this.itensVacinasCodigo;
    }
    
    public void setItensVacinasCodigo(Integer itensVacinasCodigo) {
        this.itensVacinasCodigo = itensVacinasCodigo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ITENS_VACINAS_CARTEIRA_ID", nullable=false)
    public RegistrosVacinas getRegistrosVacinas() {
        return this.registrosVacinas;
    }
    
    public void setRegistrosVacinas(RegistrosVacinas registrosVacinas) {
        this.registrosVacinas = registrosVacinas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ITENS_VACINAS_UBS_ID")
    public Ubs getUbs() {
        return this.ubs;
    }
    
    public void setUbs(Ubs ubs) {
        this.ubs = ubs;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ITENS_VACINAS_VACINAS_CODIGO", nullable=false)
    public Vacinas getVacinas() {
        return this.vacinas;
    }
    
    public void setVacinas(Vacinas vacinas) {
        this.vacinas = vacinas;
    }




}


