package br.com.sicva.model;
// Generated 16/03/2017 13:54:36 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ItensVacinas generated by hbm2java
 */
public class ItensVacinas  implements java.io.Serializable {


     private Integer itensVacinasCodigo;
     private ItensVacinas itensVacinas;
     private Ubs ubs;
     private Set itensVacinases = new HashSet(0);
     private Set registrosVacinases = new HashSet(0);

    public ItensVacinas() {
    }

    public ItensVacinas(ItensVacinas itensVacinas, Ubs ubs, Set itensVacinases, Set registrosVacinases) {
       this.itensVacinas = itensVacinas;
       this.ubs = ubs;
       this.itensVacinases = itensVacinases;
       this.registrosVacinases = registrosVacinases;
    }
   
    public Integer getItensVacinasCodigo() {
        return this.itensVacinasCodigo;
    }
    
    public void setItensVacinasCodigo(Integer itensVacinasCodigo) {
        this.itensVacinasCodigo = itensVacinasCodigo;
    }
    public ItensVacinas getItensVacinas() {
        return this.itensVacinas;
    }
    
    public void setItensVacinas(ItensVacinas itensVacinas) {
        this.itensVacinas = itensVacinas;
    }
    public Ubs getUbs() {
        return this.ubs;
    }
    
    public void setUbs(Ubs ubs) {
        this.ubs = ubs;
    }
    public Set getItensVacinases() {
        return this.itensVacinases;
    }
    
    public void setItensVacinases(Set itensVacinases) {
        this.itensVacinases = itensVacinases;
    }
    public Set getRegistrosVacinases() {
        return this.registrosVacinases;
    }
    
    public void setRegistrosVacinases(Set registrosVacinases) {
        this.registrosVacinases = registrosVacinases;
    }




}


