package br.com.sicva.model;
// Generated 16/03/2017 13:54:36 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pacientes generated by hbm2java
 */
public class Pacientes  implements java.io.Serializable {


     private Integer pacientesNumeroRegistroNascimento;
     private Enderecos enderecos;
     private Usuarios usuarios;
     private String pacientesCpf;
     private String pacientesNome;
     private String pacientesDataNascimento;
     private String pacientesNomeResponsavel;
     private String pacientesFone1;
     private String pacientesFone2;
     private Set registrosVacinases = new HashSet(0);
     private Set carteirasVacinases = new HashSet(0);

    public Pacientes() {
    }

	
    public Pacientes(String pacientesCpf) {
        this.pacientesCpf = pacientesCpf;
    }
    public Pacientes(Enderecos enderecos, Usuarios usuarios, String pacientesCpf, String pacientesNome, String pacientesDataNascimento, String pacientesNomeResponsavel, String pacientesFone1, String pacientesFone2, Set registrosVacinases, Set carteirasVacinases) {
       this.enderecos = enderecos;
       this.usuarios = usuarios;
       this.pacientesCpf = pacientesCpf;
       this.pacientesNome = pacientesNome;
       this.pacientesDataNascimento = pacientesDataNascimento;
       this.pacientesNomeResponsavel = pacientesNomeResponsavel;
       this.pacientesFone1 = pacientesFone1;
       this.pacientesFone2 = pacientesFone2;
       this.registrosVacinases = registrosVacinases;
       this.carteirasVacinases = carteirasVacinases;
    }
   
    public Integer getPacientesNumeroRegistroNascimento() {
        return this.pacientesNumeroRegistroNascimento;
    }
    
    public void setPacientesNumeroRegistroNascimento(Integer pacientesNumeroRegistroNascimento) {
        this.pacientesNumeroRegistroNascimento = pacientesNumeroRegistroNascimento;
    }
    public Enderecos getEnderecos() {
        return this.enderecos;
    }
    
    public void setEnderecos(Enderecos enderecos) {
        this.enderecos = enderecos;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getPacientesCpf() {
        return this.pacientesCpf;
    }
    
    public void setPacientesCpf(String pacientesCpf) {
        this.pacientesCpf = pacientesCpf;
    }
    public String getPacientesNome() {
        return this.pacientesNome;
    }
    
    public void setPacientesNome(String pacientesNome) {
        this.pacientesNome = pacientesNome;
    }
    public String getPacientesDataNascimento() {
        return this.pacientesDataNascimento;
    }
    
    public void setPacientesDataNascimento(String pacientesDataNascimento) {
        this.pacientesDataNascimento = pacientesDataNascimento;
    }
    public String getPacientesNomeResponsavel() {
        return this.pacientesNomeResponsavel;
    }
    
    public void setPacientesNomeResponsavel(String pacientesNomeResponsavel) {
        this.pacientesNomeResponsavel = pacientesNomeResponsavel;
    }
    public String getPacientesFone1() {
        return this.pacientesFone1;
    }
    
    public void setPacientesFone1(String pacientesFone1) {
        this.pacientesFone1 = pacientesFone1;
    }
    public String getPacientesFone2() {
        return this.pacientesFone2;
    }
    
    public void setPacientesFone2(String pacientesFone2) {
        this.pacientesFone2 = pacientesFone2;
    }
    public Set getRegistrosVacinases() {
        return this.registrosVacinases;
    }
    
    public void setRegistrosVacinases(Set registrosVacinases) {
        this.registrosVacinases = registrosVacinases;
    }
    public Set getCarteirasVacinases() {
        return this.carteirasVacinases;
    }
    
    public void setCarteirasVacinases(Set carteirasVacinases) {
        this.carteirasVacinases = carteirasVacinases;
    }




}


