package br.com.sicva.model;
// Generated 16/03/2017 15:37:02 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RegistrosVacinas generated by hbm2java
 */
@Entity
@Table(name="registros_vacinas"
    ,catalog="sicva"
)
public class RegistrosVacinas  implements java.io.Serializable {


     private Integer registrosId;
     private CarteirasVacinas carteirasVacinas;
     private ItensVacinas itensVacinas;
     private Pacientes pacientes;
     private Ubs ubs;
     private Usuarios usuarios;
     private String registrosLoteVacinas;
     private Date registrosDataAplicacaoVacina;

    public RegistrosVacinas() {
    }

    public RegistrosVacinas(CarteirasVacinas carteirasVacinas, ItensVacinas itensVacinas, Pacientes pacientes, Ubs ubs, Usuarios usuarios, String registrosLoteVacinas, Date registrosDataAplicacaoVacina) {
       this.carteirasVacinas = carteirasVacinas;
       this.itensVacinas = itensVacinas;
       this.pacientes = pacientes;
       this.ubs = ubs;
       this.usuarios = usuarios;
       this.registrosLoteVacinas = registrosLoteVacinas;
       this.registrosDataAplicacaoVacina = registrosDataAplicacaoVacina;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="REGISTROS_ID", unique=true, nullable=false)
    public Integer getRegistrosId() {
        return this.registrosId;
    }
    
    public void setRegistrosId(Integer registrosId) {
        this.registrosId = registrosId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="REGISTROS_CARTEIRAS_ID")
    public CarteirasVacinas getCarteirasVacinas() {
        return this.carteirasVacinas;
    }
    
    public void setCarteirasVacinas(CarteirasVacinas carteirasVacinas) {
        this.carteirasVacinas = carteirasVacinas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="REGISTROS_ITENS_VACINAS_CODIGO")
    public ItensVacinas getItensVacinas() {
        return this.itensVacinas;
    }
    
    public void setItensVacinas(ItensVacinas itensVacinas) {
        this.itensVacinas = itensVacinas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="REGISTROS_PACIENTES_NUMERO_REGISTRO_NASCIMENTO")
    public Pacientes getPacientes() {
        return this.pacientes;
    }
    
    public void setPacientes(Pacientes pacientes) {
        this.pacientes = pacientes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="REGISTROS_UBS_ID")
    public Ubs getUbs() {
        return this.ubs;
    }
    
    public void setUbs(Ubs ubs) {
        this.ubs = ubs;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="REGISTROS_USUARIOS_CPF")
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }

    
    @Column(name="REGISTROS_LOTE_VACINAS", length=8)
    public String getRegistrosLoteVacinas() {
        return this.registrosLoteVacinas;
    }
    
    public void setRegistrosLoteVacinas(String registrosLoteVacinas) {
        this.registrosLoteVacinas = registrosLoteVacinas;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="REGISTROS_DATA_APLICACAO_VACINA", length=10)
    public Date getRegistrosDataAplicacaoVacina() {
        return this.registrosDataAplicacaoVacina;
    }
    
    public void setRegistrosDataAplicacaoVacina(Date registrosDataAplicacaoVacina) {
        this.registrosDataAplicacaoVacina = registrosDataAplicacaoVacina;
    }




}


