package br.com.sicva.model;
// Generated 28/03/2017 16:05:59 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RegistrosVacinas generated by hbm2java
 */
@Entity
@Table(name="registros_vacinas"
    ,catalog="sicva"
)
public class RegistrosVacinas  implements java.io.Serializable {


     private int registrosId;
     private Pacientes pacientes;
     private Date registrosDataAplicacaoVacina;
     private String registrosLoteVacinas;
     private Ubs ubs;
     private Usuarios usuarios;

    public RegistrosVacinas() {
    }

	
    public RegistrosVacinas(int registrosId, Pacientes pacientes) {
        this.registrosId = registrosId;
        this.pacientes = pacientes;
    }
    public RegistrosVacinas(int registrosId, Pacientes pacientes, Date registrosDataAplicacaoVacina, String registrosLoteVacinas, Ubs ubs, Usuarios usuarios) {
       this.registrosId = registrosId;
       this.pacientes = pacientes;
       this.registrosDataAplicacaoVacina = registrosDataAplicacaoVacina;
       this.registrosLoteVacinas = registrosLoteVacinas;
       this.ubs = ubs;
       this.usuarios = usuarios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="REGISTROS_ID", unique=true, nullable=false)
    public int getRegistrosId() {
        return this.registrosId;
    }
    
    public void setRegistrosId(int registrosId) {
        this.registrosId = registrosId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="REGISTROS_PACIENTES_NUMERO_REGISTRO_NASCIMENTO", nullable=false)
    public Pacientes getPacientes() {
        return this.pacientes;
    }
    
    public void setPacientes(Pacientes pacientes) {
        this.pacientes = pacientes;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="REGISTROS_DATA_APLICACAO_VACINA", length=10)
    public Date getRegistrosDataAplicacaoVacina() {
        return this.registrosDataAplicacaoVacina;
    }
    
    public void setRegistrosDataAplicacaoVacina(Date registrosDataAplicacaoVacina) {
        this.registrosDataAplicacaoVacina = registrosDataAplicacaoVacina;
    }

    
    @Column(name="REGISTROS_LOTE_VACINAS", length=8)
    public String getRegistrosLoteVacinas() {
        return this.registrosLoteVacinas;
    }
    
    public void setRegistrosLoteVacinas(String registrosLoteVacinas) {
        this.registrosLoteVacinas = registrosLoteVacinas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="REGISTROS_UBS_ID")
    public Ubs getUbs() {
        return this.ubs;
    }
    
    public void setUbs(Ubs ubs) {
        this.ubs = ubs;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="REGISTROS_USUARIOS_CPF")
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }




}


