package br.com.sicva.model;
// Generated 16/03/2017 13:54:36 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * RegistrosVacinas generated by hbm2java
 */
public class RegistrosVacinas  implements java.io.Serializable {


     private Integer registrosId;
     private CarteirasVacinas carteirasVacinas;
     private ItensVacinas itensVacinas;
     private Pacientes pacientes;
     private Ubs ubs;
     private Usuarios usuarios;
     private String registrosLoteVacinas;
     private Date registrosDataAplicacaoVacina;

    public RegistrosVacinas() {
    }

    public RegistrosVacinas(CarteirasVacinas carteirasVacinas, ItensVacinas itensVacinas, Pacientes pacientes, Ubs ubs, Usuarios usuarios, String registrosLoteVacinas, Date registrosDataAplicacaoVacina) {
       this.carteirasVacinas = carteirasVacinas;
       this.itensVacinas = itensVacinas;
       this.pacientes = pacientes;
       this.ubs = ubs;
       this.usuarios = usuarios;
       this.registrosLoteVacinas = registrosLoteVacinas;
       this.registrosDataAplicacaoVacina = registrosDataAplicacaoVacina;
    }
   
    public Integer getRegistrosId() {
        return this.registrosId;
    }
    
    public void setRegistrosId(Integer registrosId) {
        this.registrosId = registrosId;
    }
    public CarteirasVacinas getCarteirasVacinas() {
        return this.carteirasVacinas;
    }
    
    public void setCarteirasVacinas(CarteirasVacinas carteirasVacinas) {
        this.carteirasVacinas = carteirasVacinas;
    }
    public ItensVacinas getItensVacinas() {
        return this.itensVacinas;
    }
    
    public void setItensVacinas(ItensVacinas itensVacinas) {
        this.itensVacinas = itensVacinas;
    }
    public Pacientes getPacientes() {
        return this.pacientes;
    }
    
    public void setPacientes(Pacientes pacientes) {
        this.pacientes = pacientes;
    }
    public Ubs getUbs() {
        return this.ubs;
    }
    
    public void setUbs(Ubs ubs) {
        this.ubs = ubs;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getRegistrosLoteVacinas() {
        return this.registrosLoteVacinas;
    }
    
    public void setRegistrosLoteVacinas(String registrosLoteVacinas) {
        this.registrosLoteVacinas = registrosLoteVacinas;
    }
    public Date getRegistrosDataAplicacaoVacina() {
        return this.registrosDataAplicacaoVacina;
    }
    
    public void setRegistrosDataAplicacaoVacina(Date registrosDataAplicacaoVacina) {
        this.registrosDataAplicacaoVacina = registrosDataAplicacaoVacina;
    }




}


