package br.com.sicva.model;
// Generated 16/03/2017 15:37:02 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ubs generated by hbm2java
 */
@Entity
@Table(name="ubs"
    ,catalog="sicva"
)
public class Ubs  implements java.io.Serializable {


     private Integer ubsId;
     private String ubsDescricao;
     

    public Ubs() {
    }

    public Ubs(String ubsDescricao) {
       this.ubsDescricao = ubsDescricao;       
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="UBS_ID", unique=true, nullable=false)
    public Integer getUbsId() {
        return this.ubsId;
    }
    
    public void setUbsId(Integer ubsId) {
        this.ubsId = ubsId;
    }

    
    @Column(name="UBS_DESCRICAO", length=30)
    public String getUbsDescricao() {
        return this.ubsDescricao;
    }
    
    public void setUbsDescricao(String ubsDescricao) {
        this.ubsDescricao = ubsDescricao;
    }


    

}


