package br.com.sicva.model;
// Generated 16/03/2017 13:54:36 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Ubs generated by hbm2java
 */
public class Ubs  implements java.io.Serializable {


     private Integer ubsId;
     private String ubsDescricao;
     private Set itensVacinases = new HashSet(0);
     private Set registrosVacinases = new HashSet(0);

    public Ubs() {
    }

    public Ubs(String ubsDescricao, Set itensVacinases, Set registrosVacinases) {
       this.ubsDescricao = ubsDescricao;
       this.itensVacinases = itensVacinases;
       this.registrosVacinases = registrosVacinases;
    }
   
    public Integer getUbsId() {
        return this.ubsId;
    }
    
    public void setUbsId(Integer ubsId) {
        this.ubsId = ubsId;
    }
    public String getUbsDescricao() {
        return this.ubsDescricao;
    }
    
    public void setUbsDescricao(String ubsDescricao) {
        this.ubsDescricao = ubsDescricao;
    }
    public Set getItensVacinases() {
        return this.itensVacinases;
    }
    
    public void setItensVacinases(Set itensVacinases) {
        this.itensVacinases = itensVacinases;
    }
    public Set getRegistrosVacinases() {
        return this.registrosVacinases;
    }
    
    public void setRegistrosVacinases(Set registrosVacinases) {
        this.registrosVacinases = registrosVacinases;
    }




}


