package br.com.sicva.model;
// Generated 16/03/2017 13:54:36 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Vacinas generated by hbm2java
 */
public class Vacinas  implements java.io.Serializable {


     private Integer vacinasCodigo;
     private String vacinasDescricao;
     private Set carteirasVacinases = new HashSet(0);

    public Vacinas() {
    }

    public Vacinas(String vacinasDescricao, Set carteirasVacinases) {
       this.vacinasDescricao = vacinasDescricao;
       this.carteirasVacinases = carteirasVacinases;
    }
   
    public Integer getVacinasCodigo() {
        return this.vacinasCodigo;
    }
    
    public void setVacinasCodigo(Integer vacinasCodigo) {
        this.vacinasCodigo = vacinasCodigo;
    }
    public String getVacinasDescricao() {
        return this.vacinasDescricao;
    }
    
    public void setVacinasDescricao(String vacinasDescricao) {
        this.vacinasDescricao = vacinasDescricao;
    }
    public Set getCarteirasVacinases() {
        return this.carteirasVacinases;
    }
    
    public void setCarteirasVacinases(Set carteirasVacinases) {
        this.carteirasVacinases = carteirasVacinases;
    }




}


